package translate.cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-20T11:07:01.787+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "EnglishChineseHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EnglishChineseHttpGet {

    /**
     * <br /><h3>获得候选词</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "SuggestWord")
    public ArrayOfString suggestWord(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>中英文双向翻译（基本）String()</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "TranslatorString")
    public ArrayOfString translatorString(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>中英文双向翻译（相关词条）String()</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "TranslatorReferString")
    public ArrayOfString translatorReferString(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>中英文双向翻译 DataSet</h3><p>输入参数：wordKey = 单词； 返回数据：DataSet。（包括全部数据三个DataTable）</p><br />
     */
    @WebResult(name = "DataSet", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "Translator")
    public DataSet translator(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>获得朗读MP3字节流</h3><p>输入参数：Mp3 = Mp3名称； 返回数据：字节数组 Byte[]。</p><br />
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetMp3")
    public byte[] getMp3(
        @WebParam(partName = "Mp3", name = "Mp3", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String mp3
    );

    /**
     * <br /><h3>中英文双向翻译（例句）String()</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "TranslatorSentenceString")
    public ArrayOfString translatorSentenceString(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );
}
