package translate.cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-20T11:07:01.773+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "EnglishChineseSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EnglishChineseSoap {

    /**
     * <br /><h3>获得候选词</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "SuggestWordResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "SuggestWord", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SuggestWord")
    @WebMethod(operationName = "SuggestWord", action = "http://WebXml.com.cn/SuggestWord")
    @ResponseWrapper(localName = "SuggestWordResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SuggestWordResponse")
    public cn.com.webxml.ArrayOfString suggestWord(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>中英文双向翻译（基本）String()</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "TranslatorStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "TranslatorString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorString")
    @WebMethod(operationName = "TranslatorString", action = "http://WebXml.com.cn/TranslatorString")
    @ResponseWrapper(localName = "TranslatorStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorStringResponse")
    public cn.com.webxml.ArrayOfString translatorString(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>中英文双向翻译（相关词条）String()</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "TranslatorReferStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "TranslatorReferString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorReferString")
    @WebMethod(operationName = "TranslatorReferString", action = "http://WebXml.com.cn/TranslatorReferString")
    @ResponseWrapper(localName = "TranslatorReferStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorReferStringResponse")
    public cn.com.webxml.ArrayOfString translatorReferString(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>中英文双向翻译 DataSet</h3><p>输入参数：wordKey = 单词； 返回数据：DataSet。（包括全部数据三个DataTable）</p><br />
     */
    @WebResult(name = "TranslatorResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "Translator", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.Translator")
    @WebMethod(operationName = "Translator", action = "http://WebXml.com.cn/Translator")
    @ResponseWrapper(localName = "TranslatorResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorResponse")
    public translate.cn.com.webxml.TranslatorResponse.TranslatorResult translator(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    /**
     * <br /><h3>获得朗读MP3字节流</h3><p>输入参数：Mp3 = Mp3名称； 返回数据：字节数组 Byte[]。</p><br />
     */
    @WebResult(name = "GetMp3Result", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "GetMp3", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetMp3")
    @WebMethod(operationName = "GetMp3", action = "http://WebXml.com.cn/GetMp3")
    @ResponseWrapper(localName = "GetMp3Response", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetMp3Response")
    public byte[] getMp3(
        @WebParam(name = "Mp3", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String mp3
    );

    /**
     * <br /><h3>中英文双向翻译（例句）String()</h3><p>输入参数：wordKey = 单词； 返回数据：一维字符串数组 String[]。</p><br />
     */
    @WebResult(name = "TranslatorSentenceStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "TranslatorSentenceString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorSentenceString")
    @WebMethod(operationName = "TranslatorSentenceString", action = "http://WebXml.com.cn/TranslatorSentenceString")
    @ResponseWrapper(localName = "TranslatorSentenceStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorSentenceStringResponse")
    public cn.com.webxml.ArrayOfString translatorSentenceString(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );
}
